Repository spkesDE/com.spkes.telegramNotifications, pull requests merged in 2023-08, with the labels that each got.

#55 Male to female word
  locales/it.json
Labels: enhancement

#54 SendPhoto fix
  flow/actions/sendTagImage.ts
  flow/actions/sendTagImageWithMessage.ts
Labels: bug

#51 Feature/translations
  .homeychangelog.json
  .homeycompose/app.json
  app.json
  flow/triggers/handleNewUsers.ts
  flow/triggers/handleQuestions.ts
  flow/triggers/handleTopics.ts
  locales/de.json
  locales/en.json
  locales/it.json
  locales/nl.json
  utils.ts
Labels: enhancement, Translation

#50 Feature/markdown
  app.ts
  flow/actions/deleteByCustomId.ts
  flow/actions/deleteById.ts
  flow/actions/deleteByIdAndChatId.ts
  flow/actions/sendImage.ts
  flow/actions/sendImageWithMessage.ts
  flow/actions/sendMessage.ts
  flow/actions/sendQuestion.ts
  flow/actions/sendSilentMessage.ts
  flow/actions/sendTagImage.ts
  flow/actions/sendTagImageWithMessage.ts
  locales/de.json
  locales/en.json
  locales/it.json
  locales/nl.json
  question.ts
  settings/asset-manifest.json
  settings/index.html
  telegram-settings/public/index.html
  telegram-settings/src/App.css
  telegram-settings/src/index.css
  telegram-settings/src/views/AboutMenu.tsx
  telegram-settings/src/views/DebugMenu.tsx
  telegram-settings/src/views/SettingsMenu.tsx
Labels: enhancement

#49 Feature/commands
  app.ts
  locales/de.json
  locales/en.json
  locales/it.json
  locales/nl.json
Labels: enhancement

#52 Feature/more languages
  .homeychangelog.json
  .homeycompose/app.json
  app.json
  locales/da.json
  locales/es.json
  locales/fr.json
  locales/it.json
  locales/no.json
  locales/pl.json
  locales/sv.json
  telegram-settings/src/views/AboutMenu.tsx
Labels: enhancement, Translation
